'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const handler=require('../api/index');
function call(path,headers={}){return new Promise((resolve,reject)=>{const req={method:'GET',url:path,headers:{host:'archives.example','x-forwarded-proto':'https',...headers}};const out={statusCode:200,headers:{},body:''};const res={setHeader(k,v){out.headers[String(k).toLowerCase()]=v},end(v=''){out.body+=v||'';resolve(out)},getHeader(k){return out.headers[String(k).toLowerCase()]}};Promise.resolve(handler(req,res)).catch(reject)})}

test('manifest route dynamic with provider-specific catalogs',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';try{const r=await call('/manifest.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);const m=JSON.parse(r.body);assert.equal(m.id,'com.nuvio.calendar.archives');assert.equal(m.version,'1.2.0');assert.equal(m.catalogs.length,408);assert(m.catalogs.some(c=>c.name==='Janvier 2026 — Netflix'))}finally{delete process.env.NUVIO_NOW_OVERRIDE}});

test('future Series service row makes zero upstream calls',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';const old=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw new Error('must not call upstream')};try{const r=await call('/catalog/series/archives-v2-series-netflix-2026-12.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);assert.deepEqual(JSON.parse(r.body),{metas:[]});assert.equal(r.headers['x-nuvio-calendar-period'],'archive-2026-12');assert.equal(calls,0)}finally{global.fetch=old;delete process.env.NUVIO_NOW_OVERRIDE}});

test('future Film service row makes zero upstream calls',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';const old=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw new Error('must not call upstream')};try{const r=await call('/catalog/movie/archives-v2-movie-prime-video-2026-11.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);assert.deepEqual(JSON.parse(r.body),{metas:[]});assert.equal(calls,0)}finally{global.fetch=old;delete process.env.NUVIO_NOW_OVERRIDE}});

test('nuvio collections route is directly importable with two parents',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';try{const r=await call('/nuvio-collections.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);const payload=JSON.parse(r.body);assert(Array.isArray(payload));assert.deepEqual(payload.map(x=>x.title),['📺 Séries','🎬 Films']);assert.deepEqual(payload[0].folders.map(x=>x.title),['2026','2025']);assert.equal(payload[0].folders[0].sources.length,108);assert.equal(payload[1].folders[0].sources.length,96);assert.equal(payload[0].pinToTop,true);assert.equal(payload[0].folders[0].coverImageUrl,'https://archives.example/archive-year-card.svg?year=2026&category=series')}finally{delete process.env.NUVIO_NOW_OVERRIDE}});

test('blueprint route describes the three-level hierarchy',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';try{const r=await call('/archive-blueprint.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);const b=JSON.parse(r.body);assert.equal(b.schema,'nuvio-calendar-archives-blueprint-v1.2.0');assert.equal(b.hierarchy,'parent collection -> year folder -> month/service rows');assert(Array.isArray(b.importPayload));assert.deepEqual(b.collections.map(x=>x.title),['📺 Séries','🎬 Films'])}finally{delete process.env.NUVIO_NOW_OVERRIDE}});

test('year card route can render Series and Films variants',async()=>{const s=await call('/archive-year-card.svg?year=2026&category=series');const f=await call('/archive-year-card.svg?year=2026&category=films');assert.match(s.body,/CALENDAR SÉRIES/);assert.match(f.body,/CALENDAR FILMS/)});
