'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const handler=require('../api/index');
function call(path,headers={}){return new Promise((resolve,reject)=>{const req={method:'GET',url:path,headers:{host:'archives.example','x-forwarded-proto':'https',...headers}};const out={statusCode:200,headers:{},body:''};const res={setHeader(k,v){out.headers[String(k).toLowerCase()]=v},end(v=''){out.body+=v||'';resolve(out)},getHeader(k){return out.headers[String(k).toLowerCase()]}};Promise.resolve(handler(req,res)).catch(reject)})}

test('manifest route dynamic',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';try{const r=await call('/manifest.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);const m=JSON.parse(r.body);assert.equal(m.id,'com.nuvio.calendar.archives');assert.equal(m.version,'1.1.0');assert.equal(m.catalogs.length,24)}finally{delete process.env.NUVIO_NOW_OVERRIDE}});

test('future month zero upstream calls',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';const old=global.fetch;let calls=0;global.fetch=async()=>{calls++;throw new Error('must not call upstream')};try{const r=await call('/catalog/series/archives-v1-month-2026-12.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);assert.deepEqual(JSON.parse(r.body),{metas:[]});assert.equal(r.headers['x-nuvio-calendar-period'],'archive-2026-12');assert.equal(calls,0)}finally{global.fetch=old;delete process.env.NUVIO_NOW_OVERRIDE}});

test('nuvio collections route is directly importable array',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';try{const r=await call('/nuvio-collections.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);const payload=JSON.parse(r.body);assert(Array.isArray(payload));assert.deepEqual(payload[0].folders.map(x=>x.title),['2026','2025']);assert.equal(payload[0].folders[0].sources.length,12);assert.equal(payload[0].folders[0].coverImageUrl,'https://archives.example/archive-year-card.svg?year=2026')}finally{delete process.env.NUVIO_NOW_OVERRIDE}});

test('blueprint route wraps the same import payload',async()=>{process.env.NUVIO_NOW_OVERRIDE='2026-08-24T12:28:00Z';try{const r=await call('/archive-blueprint.json',{'x-vercel-ip-timezone':'Europe/Brussels'});assert.equal(r.statusCode,200);const b=JSON.parse(r.body);assert.equal(b.schema,'nuvio-calendar-archives-blueprint-v1.1');assert(Array.isArray(b.importPayload));assert.deepEqual(b.collection.folders.map(x=>x.title),['2026','2025'])}finally{delete process.env.NUVIO_NOW_OVERRIDE}});
